name: task_manager
description: "A Complete Task Manager Project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

# all dependency input here----
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.10+1
  pin_code_fields: ^8.0.1
  delightful_toast: ^1.1.0
  cached_network_image: ^3.3.1
  image_picker: ^1.1.2
  http: ^1.2.1
  shared_preferences: ^2.2.3
  rename_app: ^1.6.1
  get: ^4.6.6
  loading_animation_widget: ^1.2.1
  shimmer: ^3.0.0
  connectivity_plus: ^5.0.2

#------------------------------

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
